# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
library-version = "1.0.0"
commons-math3 = "3.6.1"
guava = "33.3.1-jre"
junit-jupiter-engine = "5.11.3"
kotlin = "2.1.0"
kover = "0.9.3"
bcprov = "1.70"
bip39 = "1.0.9"
nexus = "2.0.0"

[libraries]
commons-math3 = { module = "org.apache.commons:commons-math3", version.ref = "commons-math3" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter-engine" }
bcprov = { module = "org.bouncycastle:bcprov-jdk15on", version.ref = "bcprov" }
bip39 = { module = "cash.z.ecc.android:kotlin-bip39", version.ref = "bip39" }

[plugins]
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
maven-publish = { id = "maven-publish" }
signing = { id = "signing" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus" }